# Generated by Django 4.2.8 on 2024-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('dni', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('localidad', models.CharField(max_length=15)),
                ('provincia', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajero', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajeros', models.CharField(max_length=25)),
                ('mes', models.CharField(max_length=15)),
                ('fichas_vendidas', models.IntegerField()),
                ('premios', models.IntegerField()),
            ],
        ),
    ]
