# Generated by Django 4.2.9 on 2024-01-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcasino', '0002_premios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premios',
            name='cvu',
            field=models.CharField(max_length=35),
        ),
    ]
